CREATE DATABASE IF NOT EXISTS exampledb;

USE exampledb;

--Tasks Table
CREATE TABLE tasks (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(300),
    done BOOLEAN NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE tasks;

SELECT * FROM tasks;

